# Handout 1
EE-556: Mathematics of Data: From Theory to Computation - Fall 2024

We review probability theory and statistics in this handout. We will also have
a basic introduction to Stochastic Gradient Descent, an extremely important
algorithm for machine learning.

<span style="font-variant:small-caps;">Instructor: Prof. Volkan Cevher</span>

In [10]:
import numpy as np

In [11]:
n = 256
p = 3
sigma = 0.1

def get_A(num=1000):
    return np.random.normal(0, 1, size=(num, n, p))

def get_w(num=1000):
    return np.random.normal(0, sigma, size=(num, n))

def get_x(num=1000):
    return np.random.normal(0, 1, size=(num, p))

def emp_vs_th(emp, th):
    print(f"Empirical: {np.mean(emp, axis=0).round(4)} +/- {np.std(emp, axis=0).round(4)} \nTheoretical: {np.array(th).round(4)}")

## Basic Probability
<span style="font-variant:small-caps;">Problem 1: The Most Useful Bound in Probability Theory</span>

Recall the definition of a probability measure. In this problem, we will rigorously prove **the** most useful bound in probability theory, the Union Bound, stating that given any $n$ events $E_1, E_2, ..., E_n$, we have
$$
P(\cup_{i=1}^n E_i) \leq \sum_{i=1}^n P(E_i).
$$
Prove the following statements.

(a) For any two events $A$ and $B$ such that $A \subseteq B$, prove that $P(A) \leq P(B)$. 

**Solution**:

(b) Prove the union bound $P(\cup_{i=1}^n E_i) \leq \sum_{i=1}^n P(E_i)$.

(Hint: For any two events $E_1$ and $E_2$, prove that $P(E_1 \cup E_2) \leq P(E_1) + P(E_2)$. For this, you can use a useful decomposition rule of sets: $E_1 \cup E_2 = (E_1 \cap E_2^c) \cup E_2$. Applying this bound recursively will finish the proof.

To use the recursive arguments, you need to write the union of $n$ events as a union of 2 events.)

**Solution:** 

## "Modeling" in the Absence of Models; Neural Networks as Universal Approximators

Recall that the least-square estimator naturally arises from the maximum likelihood estimation of 

A1. a true signal  $\mathbf{x}^\natural$,

A2. with a linear model,

A3. of added Gaussian noise.

That is, if we assume that the data $(\mathbf{a}_i , b_i) 
% \in (\mathbb{R}^{p},\mathbb{R})
\in (\mathbb{R}^p \times \mathbb{R})
$ is generated by the following relation:
\begin{equation}
{b_i} =  \langle \mathbf{a}_i , \mathbf{x}^\natural \rangle + {\mathbf{W}_i},  \quad {\mathbf{W}_i} \sim \mathcal{N}(0, \sigma^2), 
\end{equation}then
\begin{equation}
{\mathbf{x}}^\star_{ML} = \underset{\mathbf{x} \in \mathbb{R}^p}{\operatorname{arg\,min}} \frac{1}{2}|| \mathbf{b}- \mathbf{A}\mathbf{x}||_2^2
\end{equation}where $\mathbf{A}^\top = [ \mathbf{a_1}\  \mathbf{a_2}\     \cdots \ \mathbf{a_n} ]$.

Although the importance of LS estimators can hardly be overemphasized, it is still widely criticized by its restrictive setting; i.e., assuming A1-3. A natural question is: What if we drop these assumptions? For instance, what if the model is nonlinear, or there is no such thing as a true signal, or the noise is far away from Gaussian?

Neural networks [2] present a powerful framework to address these concerns with the following philosophy: First, denote the (possibly very complicated) relation between input and output by $b = h(\mathbf{a})$, where $h$ is a function from $\mathbb{R}^p \rightarrow \mathbb{R}$ and $(\mathbf{a},b)$ follows some **unknown** distribution $\mathbb{P}$. Then the function $h$ should satisfy

$$
\begin{align} \tag{1}
h = \underset{g}{\operatorname{arg\,min}}   \frac{1}{2} \mathbb{E}_{\mathbb{P}} \left( g(\mathbf{a}) - b \right)^2, \quad g \text{ any function.} 
\end{align}
$$

(**Remark:** We focus on the regression example here, while the very same idea works for classification just as well.)

Now, there are two reasons why solving (1) is not possible:

1. We do not know the distribution $\mathbb{P}$; instead, we only have samples $(\mathbf{a}_i,b_i)$ from $\mathbb{P}$.
2. We do not know how to optimize over the set of all functions.

For the first issue, we already know that we can replace the true average by the empirical average, leading to an empirical risk minimization problem. For the second, the key idea of deep learning relies on the following theorem [3]: Informally speaking,
<center>
<em>Any function $f$ can be approximated arbitrarily well by a neural network, as long as the network size is big enough.</em>
</center>
Combining these, we are lead to the empirical risk minimization of neural networks:
\begin{equation}
{\mathbf{X}}^\star =\underset{\mathbf{X}}{\operatorname{arg\,min}} \left\{ \frac{1}{n}\sum_{i=1}^n  \left( b_i - h_{\mathbf{X}} ( \mathbf{a}_i ) \right)^2   \right\}, \quad h_{\mathbf{x}}(\mathbf{a}) = \sigma \left( \mathbf{W}_k   \sigma \left( \cdots  \sigma\left(\mathbf{W}_2\sigma \left(  \mathbf{W}_1 \mathbf{a} + \boldsymbol{\mu}_1  \right)  + \boldsymbol{\mu}_2 \right) \cdots \right) + \boldsymbol{\mu}_k   \right);  \tag{2}
\end{equation}
where $\sigma$ is a "proper" activation function that requires some condition on continuity, $\mathbf{x} = (\mathbf{W}_1, \boldsymbol{\mu}_1, \mathbf{W}_2, \boldsymbol{\mu}_2, \dots, \mathbf{W}_k, \boldsymbol{\mu}_k)$, $\mathbf{W}_i \in \mathbb{R}^{d_i\times d_{i-1}}$, $\boldsymbol{\mu}_i \in \mathbb{R}^{d_i}$ and $\mathbf{a}\in\mathbb{R}^p$ (more on the notation in the lectures).
The hope is that, as long as we have enough parameters and data, the learned neural network is a good approximator for the function $h$:
$$
h_{{\mathbf{x}}^\star} \simeq h,
$$

which is true by the theorem of [3]. There are however trade-offs involved in scaling up over-parametrized networks: width helps robustness; depth helps robustness under a certain initialization but hurts it under another [5].

In conclusion, 
<center>
<em>Neural networks can be viewed as a "universal modeling" scheme where no assumption about the data distribution is made.</em>
</center>


Finally, all the above reasoning relies on the big "if" that we can optimize (2). It is an important fact that one can efficiently compute the (stochastic) **gradients** of (2) via the so-called *backpropagation* [4], and therefore one can run first-order algorithms. The details will be covered in the coming lectures and exercises.

## Randomness in Statistical Learning Problems, and Stochastic Gradient Descent

<span style="font-variant:small-caps;">Problem 3: Recognizing Different Randomness</span>

There are many different randomness in modern data science or machine learning problems. The purpose of this exercise is to help you get a deeper understanding of them.

This course is all about inferring from data, and the data from real world is often random. Besides this intrinsic randomness, another common source of randomness in modern applications is the *randomized algorithms*. It is extremely important that you have a clear picture of what randomness is truly relevant for statistical inference, and what is only for computational purposes.

Consider the Gaussian linear model from Lecture 1: Let $\mathbf{x}^\natural \in \mathbb{R}^p$ and $\mathbf{A} \in \mathbb{R}^{n\times p}$. We have observations of the form

\begin{equation}
\mathbf{b} =  \mathbf{A}\mathbf{x}^\natural + \mathbf{w}, \tag{3}
\end{equation}where $\mathbf{w} \sim \mathcal{N}(0, \sigma^2I)$ is the Gaussian noise vector. We aim to solve the maximum likelihood estimator 

\begin{equation}
{\mathbf{x}}^\star_{ML} = \underset{x \in \mathbb{R}^p}{\operatorname{arg\,min}} \left \{ f(\mathbf{X}):= \frac{1}{2n}|| \mathbf{b}- \mathbf{A}\mathbf{x}||_2^2\right\}, \tag{4}
\end{equation} 

where we have normalized the the loss function by the number of measurements $n$ (the number $\frac{1}{2}$ is just for convenience later).


(a) So far the only random component is the noise $\mathbf{w}$. Let $\mathbb{E}_{\mathbf{w}}$ denote the expectation with respect to the randomness of $\mathbf{w}$. Compute $\mathbb{E}_{\mathbf{w}}||\mathbf{b} -\mathbf{A} \mathbf{x}^\natural ||_2^2$.

**Solution:**

### Try verifying the result with code!

In [12]:
A, x = get_A(1)[0], get_x(1)[0]
w = get_w()
b = A @ x + w

emp = np.linalg.norm(b - A @ x, axis=1) ** 2
th = n * sigma ** 2
emp_vs_th(emp, th)

Empirical: 2.546 +/- 0.2292 
Theoretical: 2.56


(b) In practice, the measurement matrix $\mathbf{A}$ is often random. Assume that the entries of $\mathbf{A}$ are independent random variables with mean 0 and variance 1, and are independent of the noise $\mathbf{w}$. Let $\mathbb{E}_{\mathbf{A}}$ denote the expectation with respect to the randomness of $\mathbf{A}$. Show that
\begin{equation}
\frac{1}{n} \mathbb{E}_{A} ||\mathbf{A}\mathbf{x}||_2^2 = ||\mathbf{x}||_2^2 \forall \mathbf{x} \in \mathbb{R}^p.
\end{equation} 


(Hint: Let $\mathbf{a^\top_i}$ be a row of $\mathbf{A}$. What is $\mathbb{E}_{\mathbf{A}}|\langle \mathbf{a_i}, \mathbf{x} \rangle|^2$? Can you compute $\mathbb{E}_{\mathbf{A}} ||\mathbf{A}\mathbf{x}||_2^2$ through $\mathbb{E}_{\mathbf{A}}|\langle \mathbf{a_i}, \mathbf{x} \rangle|^2$?)

**Solution:**

### Try verifying the result with code!

In [16]:
A, x = get_A(), get_x(1)[0]
emp = np.linalg.norm(A @ x, axis=1) ** 2 / n
th = np.linalg.norm(x) ** 2
emp_vs_th(emp, th)

Empirical: 1.6445 +/- 0.147 
Theoretical: 1.6449


(c)  Show that the following useful basic inequality holds:
\begin{equation}
||\mathbf{A}({\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural) ||_2^2 \leq 2\langle \mathbf{w}, \mathbf{A}({\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural)  \rangle.
\end{equation}
(Hint: The maximum likelihood estimator minimizes the loss function, so you can compare the values of the loss function when substituting in ${\mathbf{x}}^\star_{ML}$ and any other $\mathbf{x}$.)

**Solution:**

(d)   What we ultimately care about is the estimation error: $\mathbb{E}_{\mathbf{A}, \mathbf{w}}||{\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural ||_2^2.$ In view of (b) and (c), one might be tempted to conclude that 
\begin{equation}
\mathbb{E}_{\mathbf{A}, \mathbf{w}}||{\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural ||_2^2 \leq 2\mathbb{E}_{\mathbf{A}, \mathbf{w}}\langle \mathbf{w}, \frac{1}{n}\mathbf{A}({\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural)  \rangle.
\end{equation}Please argue carefully why this argument is NOT true.
(Hint: In part (b) we considered a fixed, deterministic $\mathbf{x}$. Is ${\mathbf{x}}^\star_{ML} - \mathbf{x}^\natural$ deterministic? If not, what randomness does it depend on?)

**Solution:**

(e) We introduce the important <span style="color:red">Stochastic Gradient Descent (SGD)</span> in the exercise.

Recall Gradient Descent (GD) for minimizing (4):

- Choose $\mathbf{x}_0$ arbitrarily.
- Do $\mathbf{x}_{k+1} = \mathbf{x}_k - \alpha_k \nabla f(\mathbf{x}_k)$ for some predetermined step-sizes $\alpha_k>0$.

Recall also that for (4), the gradient at a point $\mathbf{x}$ is $\nabla f(\mathbf{x})= \frac{1}{n}\mathbf{A}^\top(\mathbf{A}\mathbf{x}-\mathbf{b})$.

Consider a randomized algorithm as follows. At the current iterate $\mathbf{x}_k$, an index $i \in \{1, 2, ..., n\}$ is selected uniformly at random. We then replace the gradient at $\mathbf{x}_k$ by the vector $(\langle \mathbf{a_i}, \mathbf{x}_k\rangle - b_i)\mathbf{a_i}$, where $\mathbf{a^\top_i}$ is the $i$-th row of $A$ and $b_i$ is the $i$-th element of $\mathbf{b}$. All other steps are the same as GD. Let $\mathbb{E}_{SGD}$ denote the expectation with respect to the randomness of this algorithm. Show that

\begin{equation}
\mathbb{E}_{SGD}\left(\langle \mathbf{a_i}, \mathbf{x}_k\rangle - b_i\right)\mathbf{a_i} = \frac{1}{n}\mathbf{A}^\top(\mathbf{A}\mathbf{x}_k-\mathbf{b}).
\end{equation} That is, the algorithm is a randomized version of Gradient Descent, hence the name.
(Hint: Recall that $\mathbf{a^\top_i}$ is a row of $\mathbf{A}$, and therefore it is a column of $\mathbf{A}^\top$.)


*Remark:* There are many reasons for using SGD instead of GD; we refer the interested students to [1] for a gentle introduction of SGD. Please do bear in mind that SGD is extremely important in practice. Ever heard of deep learning? AlphaGo? Your interest might be piqued if you know that SGD is the go-to algorithm for these state-of-the-art learning machines.

**Solution:**

### Try verifying the result with code!

In [18]:
A, x = get_A(1)[0], get_x(1)[0]
w = get_w(1)[0]
b = A @ x + w

x_sgd = np.zeros(p)
i_batch = np.random.choice(n, size=1000)
emp = ???
th = ???
emp_vs_th(emp, th)

SyntaxError: invalid syntax (4149890490.py, line 7)

(f) Under the assumptions in (b), show that 
\begin{equation}
\mathbb{E}_{\mathbf{A}, \mathbf{w}}\left(\langle \mathbf{a_i}, \mathbf{x} \rangle - b_i\right)\mathbf{a_i} = \mathbf{x}-\mathbf{x}^\natural for any \mathbf{x}
\end{equation} .

**Solution:**

### Try verifying the result with code!

In [33]:
A, x = get_A(1)[0], get_x(1)[0]
w = get_w(1)[0]
b = A @ x + w

x_sgd = get_x(1)[0]
i = np.random.choice(n, size=1)[0]

emp = 1/n * A.T @ (A @ x_sgd - b)
th = x_sgd - x
print(emp, th)

###################
# now we do the same but sample 1000 instances of A and w:
A, x = get_A(), get_x(1)[0]
w = get_w()
b = A @ x + w

x_sgd = get_x(1)[0]
i = np.random.choice(n, size=1)[0]

n = A.shape[1]           # Number of samples per instance
N = A.shape[0]           # Number of instances

# Compute residuals for all instances
A_x_sgd = np.matmul(A, x_sgd)  # Shape: (N, n)
residuals = A_x_sgd - b        # Shape: (N, n)

# Compute empirical gradients for all instances using np.einsum
# x has shape (d,), A has shape (N, n, d), residuals has shape (N, n)
emp_gradients = (1/n) * np.einsum('nij,ni->nj', A, residuals)  # Shape: (N, d)

# Theoretical difference remains the same for all instances
th = x_sgd - x  # Shape: (d,)

# Optionally, compute the average empirical gradient over all instances
avg_emp_gradient = np.mean(emp_gradients, axis=0)  # Shape: (d,)

# print("Empirical Gradients for all instances:\n", emp_gradients)
print("Average Empirical Gradient:\n", avg_emp_gradient)
print("Theoretical Difference (x_sgd - x):\n", th)

[-0.1811155   0.64035805 -3.71664926] [-0.23213879  0.37888473 -3.14654452]
Empirical Gradients for all instances:
 [[-3.89420172  2.1227748  -1.57517874]
 [-3.44566679  1.98613156 -2.20201137]
 [-3.37752332  1.80121231 -1.4729342 ]
 ...
 [-3.31714501  1.65600202 -1.39294835]
 [-4.07118741  2.48052817 -2.19035131]
 [-3.05315922  1.65734767 -1.4065823 ]]
Average Empirical Gradient:
 [-3.64745851  1.99735689 -1.66375184]
Theoretical Difference (x_sgd - x):
 [-3.65345906  1.99726915 -1.66041234]


(g)  Under the assumptions in (b), show that, for any $\mathbf{x}$, 
\begin{equation}
\frac{1}{n}\mathbb{E}_{\mathbf{A}, \mathbf{w}}\mathbf{A}^\top(\mathbf{A}\mathbf{x}-\mathbf{b}) = \mathbf{x}-\mathbf{x}^\natural.
\end{equation}

(Hint: There are many ways of proving this. Combining (e) and (f) gives a very simple proof.)

**Solution:**

### Try verifying the result with code!

In [ ]:
A, x = get_A(), get_x(1)[0]
w = get_w()
b = A @ x + w

x_sgd = get_x(1)[0]
emp = ???
th = ???
emp_vs_th(emp, th)

## Multinomial logistic regression and language model training

<span style="font-variant:small-caps;">Problem 4: Towards training language models</span>

Recall that in the lecture we talk about logistic regression for binary classification problems. Let $\mathbf{x}^\natural \in \mathbb{R}^p$. Let $\mathbf{a}_1, \ldots, \mathbf{a}_n \in \mathbb{R}^p$ be given. The sample is given by $\mathbf{b} := ( b_1, \ldots, b_n ) \in \left\{ 0, 1 \right\}^n$. The classifier $h_\mathbf{X}$ estimates the probability $P(b = 1)$ by outputing a scalar $h_\mathbf{X}$ such that $h_\mathbf{X}:= \left[ 1 + \exp \left( - \left\langle \mathbf{a}_i, \mathbf{x} \right\rangle \right) \right]^{-1} =  P(b = 1)$.

(a)  Show that maximizing the likelihood is equivalent to minimizing the cross-entropy between the real distribution and estimated distribution.

**Solution:**

(b) In logistic regression, we only deal with two classes. But in reality, there are many situations where multiple classes are involved. In this case, we need to generalize the logistic regression to multinomial logistic regression (sometimes called the softmax regression). 

Suppose there are $K$ classes ($K\ge2$). The classifier aims to output a vector $\mathbf{h}_\mathbf{X} \in \mathbb{R}^K$ to estimate the probability of each class such that its $k$ element is $ P(b = k|\mathbf{a})$.
Note that in this case, the classifier is parameterized by a learnable matrix $\mathbf{X} \in \mathbb{R}^{K \times p}$ to estimate the probability as follows: $P(b = k|\mathbf{a} ) = (\text{Softmax}(\mathbf{X} \mathbf{a}))^{[k]}, \text{for } k \in [K]$, where Softmax is defined by:
$$ \text{Softmax}(\mathbf{X} \bf \mathbf{a}) = \begin{bmatrix} 
    \frac{\exp{((\mathbf{X} \bf \mathbf{a})^{[1]})}}
    {
        \sum_{i=1}^{K}
        \exp{((\mathbf{X} \mathbf{a})^{[i]})}
    }
    \\ \vdots \\
    \frac{\exp{((\mathbf{X} \mathbf{a})^{[K]})}}
    {
        \sum_{i=1}^{K}
        \exp{((\mathbf{X} \mathbf{a})^{[i]})}
    }
\end{bmatrix} \in R^K.$$

Again, show that maximizing the likelihood is equivalent to minimizing the cross entropy between the real distribution and the estimated
distribution.

**Solution:**

(c) To some extent, training a language model is essentially tackling a multinomial logistic regression problem where the model needs to predict next word given previous words. 
A neural network $\mathbf{h}_{\mathbf{X}}$ parameterized by $\mathbf{X}$ is used as an ML estimator, as mentioned in the lecture. Specifically, $\mathbf{h}_{\mathbf{X}}$ aims to predict the $t$ token given $t-1$ tokens.
\begin{equation*}
    \begin{split}
        & 
        \min_{\mathbf{X}}
        - \log \text{p}_{\mathbf{X}} (\mathbf{b}_{1:T})=
            - \log \left( 
                \prod_{t=1}^{T} \text{p}_{\mathbf{X}}(\mathbf{b}_t|\mathbf{b}_{1:t-1})
            \right) 
        = 
            \sum_{t=1}^{T} \left(
                -\log \text{p}_{\mathbf{X}}(\mathbf{b}_t|\mathbf{b}_{1:t-1})
            \right)
        \\ & = 		
            \sum_{t=1}^{T} \left(
                -\log \mathbf{h}_{\mathbf{X}}(\mathbf{b}_{1:t-1})^{["\mathbf{b}_t"]}
            \right)
        =  \text{cross entropy loss}.
    \end{split}
\end{equation*}


Write down the SGD algorithm for training a language model given a corpus that consists of $n$ sentences.

**Solution:**

## References 

[1] LÉON BOTTOU Stochastic Gradient Descent Tricks, Neural Networks: Tricks of the Trade, page 421-436, Springer 2012.

[2] SIMON HAYKIN Neural networks: a comprehensive foundation, Prentice Hall PTR 1994.

[3] ANDREW BARRON Universal approximation bounds for superpositions of a sigmoidal function, IEEE Transactions on Information theory,
1993.

[4] DAVID RUMELHART, GEOFFREY HINTON, AND RONALD WILLIAMS Learning representations by back-propagating errors, Cognitive
modeling, 1988.

[5] Zhu, Z., Liu, F., Chrysos, G. & Cevher, V. Robustness in deep learning: The good (width), the bad (depth), and the ugly (initialization).
ArXiv Preprint ArXiv:2209.07263. (2022)
